<?php

/**
 * @file
 * Contains family_tree_generator.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function family_tree_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the family_tree_generator module.
    case 'help.page.family_tree_generator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates and maintains family trees') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_install().
 */
function family_tree_generator_install() {
	// Create a surname vocabulary
    $vid = "surnames";
    $name = "Surnames";
    $vocabularies = \Drupal\taxonomy\Entity\Vocabulary::loadMultiple();
    if (!isset($vocabularies[$vid])) {
      $vocabulary = \Drupal\taxonomy\Entity\Vocabulary::create(array(
            'vid' => $vid,
            'machine_name' => $vid,
            'name' => $name,
      ));
      $vocabulary->save();
    }
    else {
      // Vocabulary Already exist
      $query = \Drupal::entityQuery('taxonomy_term');
      $query->condition('vid', $vid);
      $tids = $query->execute();
    }
}
